### ISSUE TITLE
bootstrap dropout is 0 at evaluation

### ISSUE THREAD

**Issue by hiyamgh** [hutec/UncertaintyNN#3]
Hello @hutec 

Great work really!! 

I wanted to ask why is dropout 0 in here:

```
feed_dict = {x_placeholder: x_eval,
                 dropout_placeholder: 0,
                 mask_placeholder: np.ones(shape=(len(x_eval), n_heads, 1))}
```

This is from the [following code](https://github.com/hutec/UncertaintyNN/blob/master/evaluation/bootstrap_evaluation.py)

Shouldn't it be equal to ```dropout```?

**Comment by hutec** [comment]
Hi @hiyamgh 

In this method, dropout is disabled during evaluation. It's only used during training as regularization. The diversity of outputs we need to calculate mean and standard deviation comes from the multiple heads.
